# Generated by Django 4.1.3 on 2022-11-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ciry',
            new_name='city',
        ),
    ]
